spring.application.name=EcoRadar

spring.datasource.url=jdbc:postgresql://localhost:5432/ecoradar
spring.datasource.username=postgres
spring.datasource.password=post
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.testWhileIdle=true
spring.jpa.hibernate.ddl-auto=update